"use client";

import { useMemo, useState } from "react";
import type { Difficulty, TrainingResult } from "@/features/cognitive-engine/types";
import { saveResult } from "@/features/progress-engine/storage";

type LanguageMode = "Synonyme" | "Kategorien" | "Satzbau" | "Wortfindung";
type LanguageTask = { id:string; mode:LanguageMode; title:string; instruction:string; prompt:string; options:string[]; answer:string; explanation:string; accent:"coral"|"indigo"|"sage"|"gold" };

const levels:{value:Difficulty;label:string;copy:string}[]=[
{value:"einstieg",label:"Einstieg",copy:"Klare Begriffe und kurze Sätze."},{value:"leicht",label:"Leicht",copy:"Vertraute Wörter mit feinen Unterschieden."},{value:"mittel",label:"Mittel",copy:"Mehrdeutigkeit und komplexere Beziehungen."},{value:"schwer",label:"Schwer",copy:"Präzise Bedeutung und anspruchsvoller Satzbau."},{value:"profi",label:"Profi",copy:"Nuancen, Logik und sprachliche Flexibilität."}];
const modes:{key:LanguageMode;icon:string;copy:string}[]=[
{key:"Synonyme",icon:"≈",copy:"Bedeutungsnähe und Wortgefühl"},{key:"Kategorien",icon:"⌘",copy:"Begriffe ordnen und Zusammenhänge erkennen"},{key:"Satzbau",icon:"↦",copy:"Wörter in eine klare Struktur bringen"},{key:"Wortfindung",icon:"Aa",copy:"Passende Begriffe präzise auswählen"}];

const lib:Record<Difficulty,LanguageTask[]>={
einstieg:[
{id:"la-e-1",mode:"Synonyme",title:"Sanfte Wortnähe",instruction:"Welches Wort bedeutet fast dasselbe?",prompt:"fröhlich",options:["traurig","heiter","müde","leise"],answer:"heiter",explanation:"Heiter und fröhlich beschreiben eine positive Stimmung.",accent:"gold"},
{id:"la-e-2",mode:"Kategorien",title:"Gemeinsame Gruppe",instruction:"Welcher Begriff gehört dazu?",prompt:"Apfel · Birne · Pflaume · ?",options:["Karotte","Kirsche","Brot","Reis"],answer:"Kirsche",explanation:"Alle Begriffe sind Obstsorten.",accent:"sage"},
{id:"la-e-3",mode:"Satzbau",title:"Klarer Satzfluss",instruction:"Welche Reihenfolge ergibt einen korrekten Satz?",prompt:"heute · im Park · wir · spazieren",options:["Wir spazieren heute im Park.","Heute wir im Park spazieren.","Im Park heute spazieren wir.","Spazieren im Park wir heute."],answer:"Wir spazieren heute im Park.",explanation:"Subjekt und Verb stehen klar am Anfang, Zeit und Ort folgen logisch.",accent:"coral"},
{id:"la-e-4",mode:"Wortfindung",title:"Passendes Wort",instruction:"Welches Wort ergänzt den Satz?",prompt:"Der Tee ist noch sehr ___.",options:["warm","laut","rund","schnell"],answer:"warm",explanation:"Warm beschreibt hier sinnvoll die Temperatur des Tees.",accent:"indigo"}],
leicht:[
{id:"la-l-1",mode:"Synonyme",title:"Feiner Unterschied",instruction:"Wähle das ähnlichste Wort.",prompt:"rasch",options:["langsam","schnell","schwer","ruhig"],answer:"schnell",explanation:"Rasch und schnell sind nahezu bedeutungsgleich.",accent:"gold"},
{id:"la-l-2",mode:"Kategorien",title:"Begriffsfamilie",instruction:"Welcher Begriff passt nicht in die Gruppe?",prompt:"Hammer · Säge · Zange · Kissen",options:["Hammer","Säge","Zange","Kissen"],answer:"Kissen",explanation:"Hammer, Säge und Zange sind Werkzeuge.",accent:"sage"},
{id:"la-l-3",mode:"Satzbau",title:"Zeit und Handlung",instruction:"Welche Formulierung ist korrekt?",prompt:"Morgen / besuchen / wir / das Museum",options:["Morgen besuchen wir das Museum.","Wir Morgen das Museum besuchen.","Besuchen Morgen wir Museum das.","Das Museum wir besuchen Morgen."],answer:"Morgen besuchen wir das Museum.",explanation:"Das Zeitwort kann vorne stehen, danach folgt das Verb an zweiter Stelle.",accent:"coral"},
{id:"la-l-4",mode:"Wortfindung",title:"Präzise Ergänzung",instruction:"Welches Verb passt am besten?",prompt:"Die Glocke ___ zur vollen Stunde.",options:["klingt","schreibt","malt","wächst"],answer:"klingt",explanation:"Eine Glocke klingt oder läutet.",accent:"indigo"}],
mittel:[
{id:"la-m-1",mode:"Synonyme",title:"Bedeutungsnuance",instruction:"Welcher Begriff kommt der Bedeutung am nächsten?",prompt:"behutsam",options:["vorsichtig","heftig","zufällig","plötzlich"],answer:"vorsichtig",explanation:"Behutsam beschreibt ein vorsichtiges, schonendes Vorgehen.",accent:"gold"},
{id:"la-m-2",mode:"Kategorien",title:"Abstrakte Ordnung",instruction:"Welche Kategorie verbindet die Begriffe?",prompt:"Mut · Geduld · Ehrlichkeit",options:["Tugenden","Werkzeuge","Farben","Orte"],answer:"Tugenden",explanation:"Alle drei Begriffe bezeichnen positive Charaktereigenschaften.",accent:"sage"},
{id:"la-m-3",mode:"Satzbau",title:"Nebensatz erkennen",instruction:"Welcher Satz ist grammatikalisch korrekt?",prompt:"obwohl / regnete / es / gingen / wir / hinaus",options:["Obwohl es regnete, gingen wir hinaus.","Obwohl regnete es, wir gingen hinaus.","Wir obwohl es regnete gingen hinaus.","Es regnete obwohl, gingen wir hinaus."],answer:"Obwohl es regnete, gingen wir hinaus.",explanation:"Im Nebensatz steht das Verb am Ende, danach folgt der Hauptsatz.",accent:"coral"},
{id:"la-m-4",mode:"Wortfindung",title:"Kontext lesen",instruction:"Welches Wort trifft die Aussage am genauesten?",prompt:"Nach langer Diskussion fanden beide Seiten einen ___.",options:["Kompromiss","Umweg","Verdacht","Widerspruch"],answer:"Kompromiss",explanation:"Ein Kompromiss ist eine gemeinsame Lösung nach unterschiedlichen Positionen.",accent:"indigo"}],
schwer:[
{id:"la-s-1",mode:"Synonyme",title:"Präzise Sprache",instruction:"Welcher Begriff ist am ähnlichsten?",prompt:"ambivalent",options:["zwiespältig","eindeutig","gleichgültig","überstürzt"],answer:"zwiespältig",explanation:"Ambivalent bedeutet, gleichzeitig gegensätzliche Gefühle oder Bewertungen zu haben.",accent:"gold"},
{id:"la-s-2",mode:"Kategorien",title:"Oberbegriff finden",instruction:"Welcher Oberbegriff passt am besten?",prompt:"Roman · Gedicht · Drama · Essay",options:["Literaturgattungen","Musikstile","Berufe","Zeitepochen"],answer:"Literaturgattungen",explanation:"Alle vier Begriffe bezeichnen Formen literarischer Texte.",accent:"sage"},
{id:"la-s-3",mode:"Satzbau",title:"Logische Verbindung",instruction:"Welcher Satz ist stilistisch und logisch am klarsten?",prompt:"Sie war müde. Sie beendete dennoch die Aufgabe.",options:["Obwohl sie müde war, beendete sie die Aufgabe.","Sie war müde, weil sie die Aufgabe beendete dennoch.","Müde war sie, die Aufgabe dennoch beendete.","Die Aufgabe war müde, dennoch beendete sie."],answer:"Obwohl sie müde war, beendete sie die Aufgabe.",explanation:"Der Gegensatz wird mit obwohl klar und korrekt verbunden.",accent:"coral"},
{id:"la-s-4",mode:"Wortfindung",title:"Bedeutung im Kontext",instruction:"Welches Wort vervollständigt den Satz präzise?",prompt:"Die neue Studie ___ die bisherige Annahme.",options:["widerlegt","schmückt","verschiebt","begrüßt"],answer:"widerlegt",explanation:"Eine Studie kann eine Annahme durch neue Belege widerlegen.",accent:"indigo"}],
profi:[
{id:"la-p-1",mode:"Synonyme",title:"Sprachliche Feinheit",instruction:"Welcher Begriff entspricht der Bedeutung am genauesten?",prompt:"konzis",options:["prägnant","weitschweifig","ungewiss","bildhaft"],answer:"prägnant",explanation:"Konzis bedeutet knapp, klar und auf das Wesentliche beschränkt.",accent:"gold"},
{id:"la-p-2",mode:"Kategorien",title:"Semantisches Netz",instruction:"Welche Beziehung verbindet die Begriffe?",prompt:"These · Antithese · Synthese",options:["dialektische Schritte","grammatische Zeiten","geografische Räume","musikalische Intervalle"],answer:"dialektische Schritte",explanation:"Die Begriffe beschreiben ein klassisches dialektisches Denkmodell.",accent:"sage"},
{id:"la-p-3",mode:"Satzbau",title:"Komplexe Syntax",instruction:"Welche Formulierung ist korrekt und präzise?",prompt:"Die Ergebnisse waren unerwartet. Deshalb wurde die Hypothese erneut geprüft.",options:["Da die Ergebnisse unerwartet waren, wurde die Hypothese erneut geprüft.","Die Hypothese, weil unerwartet Ergebnisse, wurde erneut geprüft.","Unerwartet waren Ergebnisse deshalb die Hypothese geprüft.","Erneut geprüft die Hypothese, Ergebnisse unerwartet."],answer:"Da die Ergebnisse unerwartet waren, wurde die Hypothese erneut geprüft.",explanation:"Der Kausalsatz verbindet Ursache und Folge grammatikalisch eindeutig.",accent:"coral"},
{id:"la-p-4",mode:"Wortfindung",title:"Begriffliche Präzision",instruction:"Welches Wort passt am genauesten?",prompt:"Die Aussage war so formuliert, dass mehrere Deutungen möglich blieben; sie war ___.",options:["mehrdeutig","redundant","wortgetreu","chronologisch"],answer:"mehrdeutig",explanation:"Mehrdeutig bezeichnet eine Aussage mit mehreren möglichen Interpretationen.",accent:"indigo"}]};

function makeId(){return typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`language-${Date.now()}`}

export function LanguageLab(){
 const [difficulty,setDifficulty]=useState<Difficulty>("leicht"); const [mode,setMode]=useState<LanguageMode>("Synonyme"); const [selected,setSelected]=useState<string|null>(null); const [finished,setFinished]=useState(false); const [startedAt,setStartedAt]=useState(Date.now());
 const task=useMemo(()=>lib[difficulty].find(t=>t.mode===mode)!,[difficulty,mode]); const isCorrect=selected===task.answer;
 function reset(d=difficulty,m=mode){setDifficulty(d);setMode(m);setSelected(null);setFinished(false);setStartedAt(Date.now())}
 function submit(option:string){if(selected)return;setSelected(option);const result:TrainingResult={id:makeId(),domain:"sprache",difficulty,score:option===task.answer?100:35,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),createdAt:new Date().toISOString(),exerciseId:task.id,exerciseType:"language-scene",category:mode};saveResult(result)}
 return <>
 <section className="panel language-hero"><div><span className="eyebrow">Language Lab 1.0 · Premium Learning Experience</span><h1>Sprache wird zur Entdeckungsreise.</h1><p className="lead">Wörter, Bedeutungen und Sätze erscheinen nicht als trockenes Arbeitsblatt, sondern als ruhige, lebendige Sprachwelten mit klarer Orientierung.</p></div><div className="language-sculpture" aria-hidden="true"><span>A</span><span>Wort</span><span>↦</span><b>SPRACHE</b></div></section>
 <section className="panel logic-controls"><span className="eyebrow">Schwierigkeitsgrad</span><div className="difficulty-grid">{levels.map(l=><button key={l.value} className={`difficulty-card ${difficulty===l.value?"is-active":""}`} onClick={()=>reset(l.value,mode)}><strong>{l.label}</strong><span>{l.copy}</span></button>)}</div><span className="eyebrow logic-mode-label">Sprachwelt</span><div className="logic-mode-grid">{modes.map(item=><button key={item.key} className={`logic-mode-card language-mode ${mode===item.key?"is-active":""}`} onClick={()=>reset(difficulty,item.key)}><i>{item.icon}</i><strong>{item.key}</strong><span>{item.copy}</span></button>)}</div></section>
 {finished?<section className="panel language-summary"><span className="eyebrow">Training abgeschlossen</span><div className="language-score"><strong>{isCorrect?"100":"35"}%</strong><span>Sprachleistung</span></div><h2>{isCorrect?"Treffsicher formuliert.":"Bedeutung neu verankert."}</h2><p>{isCorrect?"Du hast Bedeutung und Kontext präzise verbunden.":task.explanation}</p><button className="btn btn-primary" onClick={()=>reset()}>Neue Sprachszene</button></section>:
 <section className={`language-stage language-${task.accent}`}><div className="logic-stage-head"><div><span className="eyebrow">{mode} · {difficulty}</span><h2>{task.title}</h2><p>{task.instruction}</p></div><div className="runner-counter">1 / 1</div></div><div className="language-line"><span/></div><div className="language-prompt"><small>FOKUSWORT / SATZ</small><strong>{task.prompt}</strong></div><div className="language-options">{task.options.map(o=><button key={o} disabled={!!selected} className={`${selected===o?"is-selected":""} ${selected&&o===task.answer?"is-correct":""} ${selected===o&&!isCorrect?"is-wrong":""}`} onClick={()=>submit(o)}>{o}</button>)}</div>{selected&&<div className={`logic-feedback ${isCorrect?"is-correct":"is-wrong"}`}><div className="feedback-mark">{isCorrect?"✓":"↺"}</div><div><strong>{isCorrect?"Sprachgefühl bestätigt":"Neue Bedeutungsspur"}</strong><p>{task.explanation}</p></div></div>}<div className="logic-actions"><span>{selected?"Erklärung geprüft":"Wähle die sprachlich passendste Antwort"}</span>{selected&&<button className="btn btn-primary" onClick={()=>setFinished(true)}>Auswertung öffnen</button>}</div></section>}
 </>;
}
