import { createSessionSeed, difficultyFromPercent, finalizeBalancedSessionTasks, randomInt, shuffled, type Difficulty } from "@/lib/dynamicTraining";
import { LOGIC_SESSION_LENGTH, LOGIC_STORAGE_KEY, type LogicMode, type LogicSession, type LogicTask } from "@/lib/logic";

export { LOGIC_SESSION_LENGTH, LOGIC_STORAGE_KEY };
export type { LogicMode, LogicSession, LogicTask };

function makeTask(id:string,mode:LogicMode,prompt:string,detail:string,correct:string,distractors:string[],explanation:string):LogicTask{
 const options=shuffled([correct,...distractors.filter(x=>x!==correct)]).slice(0,4); return {id,mode,prompt,detail,options,answer:options.indexOf(correct),explanation};
}
function sequence(seed:number,d:Difficulty):LogicTask{
 const v=seed%(d===3?6:d===2?5:3);
 if(v===0){const a=randomInt(2,10),s=randomInt(2,d===1?6:9),xs=[0,1,2,3,4].map(i=>a+i*s),c=a+5*s;return makeTask(`v4-seq-add-${a}-${s}`,"sequence","Welche Zahl folgt?",`${xs.join(" · ")} · ?`,String(c),[String(c+s),String(c-1),String(c+1)],`Konstanter Abstand +${s}.`)}
 if(v===1){const a=randomInt(30,70),s=randomInt(2,8),xs=[0,1,2,3,4].map(i=>a-i*s),c=a-5*s;return makeTask(`v4-seq-sub-${a}-${s}`,"sequence","Welche Zahl folgt?",`${xs.join(" · ")} · ?`,String(c),[String(c+s),String(c-s),String(c+1)],`Konstanter Abstand −${s}.`)}
 if(v===2){const a=randomInt(1,5),s=randomInt(2,5),xs=[a,a+s,a+3*s,a+6*s,a+10*s],c=a+15*s;return makeTask(`v4-seq-gap-${a}-${s}`,"sequence","Setze die Folge mit wachsenden Abständen fort.",`${xs.join(" · ")} · ?`,String(c),[String(c-s),String(c+s),String(c-1)],`Abstände: +${s}, +${2*s}, +${3*s}, +${4*s}, +${5*s}.`)}
 if(v===3){const a=randomInt(2,5),b=randomInt(2,6),xs=[a,b,a+b,a+2*b,2*a+3*b],c=3*a+5*b;return makeTask(`v4-seq-fib-${a}-${b}`,"sequence","Welche Zahl folgt in der rekursiven Reihe?",`${xs.join(" · ")} · ?`,String(c),[String(c-1),String(c+1),String(c+a)],"Jede Zahl ist die Summe der beiden vorherigen.")}
 if(v===4){const a=randomInt(2,5),xs=[a,a*2,a*2+1,(a*2+1)*2,(a*2+1)*2+1],c=((a*2+1)*2+1)*2;return makeTask(`v4-seq-alt-${a}`,"sequence","Welche Zahl folgt beim Wechselmuster?",`${xs.join(" · ")} · ?`,String(c),[String(c+1),String(c-2),String(c/2)],"Die Operationen wechseln: ×2, +1, ×2, +1, ×2.")}
 const a=randomInt(2,5),xs=[a,a*a,a*a+2,(a*a+2)*2,(a*a+2)*2+3],c=((a*a+2)*2+3)*2;return makeTask(`v4-seq-mix-${a}`,"sequence","Welche Zahl setzt das Mehrschritt-Muster fort?",`${xs.join(" · ")} · ?`,String(c),[String(c+2),String(c-3),String(c/2)],"Nach dem Start wechseln strukturierte Multiplikations- und Additionsschritte.")
}
function rule(seed:number,d:Difficulty):LogicTask{
 const x=randomInt(3,9),v=seed%(d===3?6:d===2?5:3),m=randomInt(2,5),a=randomInt(1,6);
 if(v===0){const c=x*m+a;return makeTask(`v4-rule-ma-${m}-${a}-${x}`,"rule","Welche Ausgabe ist korrekt?",`2 → ${2*m+a} · 4 → ${4*m+a} · ${x} → ?`,String(c),[String(x*m),String(c+m),String(c-1)],`×${m}, danach +${a}.`)}
 if(v===1){const c=x*m-a;return makeTask(`v4-rule-ms-${m}-${a}-${x}`,"rule","Erkenne die Regel.",`3 → ${3*m-a} · 5 → ${5*m-a} · ${x} → ?`,String(c),[String(x*m),String(c+a),String(c-1)],`×${m}, danach −${a}.`)}
 if(v===2){const c=(x+a)*m;return makeTask(`v4-rule-am-${a}-${m}-${x}`,"rule","Welche Ausgabe folgt?",`2 → ${(2+a)*m} · 4 → ${(4+a)*m} · ${x} → ?`,String(c),[String(x*m+a),String(c+m),String(c-a)],`Zuerst +${a}, danach ×${m}.`)}
 if(v===3){const c=x*x+2;return makeTask(`v4-rule-square-${x}`,"rule","Welche Ausgabe passt zum Muster?",`2 → 6 · 3 → 11 · ${x} → ?`,String(c),[String(x*x),String(c+x),String(c-1)],"Zahl quadrieren und 2 addieren.")}
 if(v===4){const c=x*(x+1);return makeTask(`v4-rule-product-${x}`,"rule","Welche Ausgabe passt?",`2 → 6 · 4 → 20 · ${x} → ?`,String(c),[String(x*x),String(c+x),String(c-1)],"Eine Zahl wird mit ihrem direkten Nachfolger multipliziert.")}
 const c=x*x-x+3;return makeTask(`v4-rule-hard-${x}`,"rule","Welche Ausgabe folgt aus der zusammengesetzten Regel?",`3 → 9 · 4 → 15 · ${x} → ?`,String(c),[String(x*x),String(c+x),String(c-3)],"Regel: x² − x + 3.")
}
const ANALOGIES=[
 ["Auge : sehen = Ohr : ?","hören",["laufen","greifen","riechen"],"Sinnesorgan und Funktion."],["Schlüssel : Schloss = Passwort : ?","Konto",["Tisch","Fenster","Stift"],"Mittel und geschützter Zugang."],["Kapitel : Buch = Szene : ?","Film",["Karte","Stuhl","Wolke"],"Bestandteil und Ganzes."],["Thermometer : Temperatur = Uhr : ?","Zeit",["Gewicht","Länge","Lautstärke"],"Messgerät und Messgröße."],["Frage : Antwort = Problem : ?","Lösung",["Pause","Farbe","Geräusch"],"Ausgangslage und Auflösung."],["Autor : Buch = Komponist : ?","Musikstück",["Gebäude","Landkarte","Werkzeug"],"Urheber und Werk."],["Ziegel : Mauer = Wort : ?","Satz",["Ton","Zahl","Farbe"],"Element und Struktur."],["Kompass : Richtung = Kalender : ?","Datum",["Gewicht","Tonhöhe","Farbe"],"Instrument und angezeigte Information."],["Ursache : Wirkung = Frage : ?","Antwort",["Pause","Geruch","Form"],"Auslöser und Ergebnis."],["Fundament : Haus = Wurzel : ?","Baum",["Wolke","Straße","Uhr"],"Tragende Basis und Ganzes."],["Pilot : Flugzeug = Kapitän : ?","Schiff",["Zug","Fahrrad","Haus"],"Führende Person und Fahrzeug."],["Linse : Kamera = Mikrofon : ?","Aufnahme",["Treppe","Karte","Gewicht"],"Bauteil bzw. Werkzeug und typische Funktion."]
] as const;
function analogy(seed:number,d:Difficulty){const offset=d===1?0:d===2?4:8,v=ANALOGIES[(offset+seed%(d===1?6:4))%ANALOGIES.length];return makeTask(`v4-ana-${v[0]}`,"analogy","Ergänze die Analogie.",v[0],v[1],[...v[2]],v[3])}
const DED=[
 ["Alle Neri sind Luma. Taro ist ein Neri.","Taro ist ein Luma",["Taro ist kein Luma","Alle Luma sind Neri","Nichts folgt"],"Direkte Mengeninklusion."],["Kein Selo ist schwer. Mira ist ein Selo.","Mira ist nicht schwer",["Mira ist schwer","Alles Leichte ist Selo","Mira ist rot"],"Die Eigenschaft schwer ist ausgeschlossen."],["Alle Karo sind schnell. Kein schnelles Wesen ist träge. Ria ist ein Karo.","Ria ist nicht träge",["Ria ist träge","Ria ist langsam","Alle Nicht-Trägen sind Karo"],"Zweistufige Schlusskette."],["Einige Varo sind Musiker. Alle Musiker üben.","Einige Varo üben",["Alle Varo üben","Kein Varo übt","Alle Übenden sind Musiker"],"Existenz plus Inklusion."],["Alle P sind Q. Kein Q ist R. X ist P.","X ist nicht R",["X ist R","Alle R sind P","Kein P ist Q"],"P→Q und Q schließt R aus."],["Einige D sind E. Alle E sind F.","Einige D sind F",["Alle D sind F","Kein D ist F","Alle F sind E"],"Existierende E-Teilgruppe gehört zu F."],["Alle A sind B. Alle B sind C. Kein C ist D. X ist A.","X ist nicht D",["X ist D","Alle D sind A","Kein A ist B"],"Dreistufige Kette A→B→C; C schließt D aus."],["Einige H sind J. Alle J sind K. Kein K ist L.","Einige H sind nicht L",["Alle H sind K","Alle L sind H","Kein H ist J"],"Die existierenden H∩J liegen in K und damit außerhalb L."],["Alle R sind S. Einige T sind R. Alle S sind U.","Einige T sind U",["Alle T sind U","Kein T ist U","Alle U sind R"],"Die existierenden T∩R folgen über S nach U."],["Kein M ist N. Alle P sind M. Einige P sind Q.","Einige Q sind nicht N",["Alle Q sind M","Einige N sind P","Alle P sind N"],"Die existierenden P∩Q sind M und daher nicht N."]
] as const;
function deduction(seed:number,d:Difficulty){const start=d===1?0:d===2?2:6,span=d===1?3:d===2?4:4,v=DED[start+seed%span];return makeTask(`v4-ded-${v[0]}`,"deduction","Welche Aussage folgt sicher?",v[0],v[1],[...v[2]],v[3])}
function matrix(seed:number,d:Difficulty){const s=["●","▲","■","◆","✦","⬟","⬢","◇"],[a,b,c,d4]=shuffled(s).slice(0,4),v=seed%(d===3?4:3);if(v===0)return makeTask(`v4-mat-swap-${a}${b}`,"matrix","Welches Symbol ergänzt die Matrix?",`${a} ${b} | ${b} ${a} | ${a} ?`,b,s.filter(x=>x!==b).slice(0,3),"Die Paare tauschen ihre Positionen.");if(v===1)return makeTask(`v4-mat-rot-${a}${b}${c}`,"matrix","Ergänze die Rotationsmatrix.",`${a} ${b} ${c} | ${b} ${c} ${a} | ${c} ${a} ?`,b,s.filter(x=>x!==b).slice(0,3),"Jede Gruppe rotiert um eine Position.");if(v===2)return makeTask(`v4-mat-chain-${a}${b}${c}`,"matrix","Welche Form fehlt?",`${a} ${a} ${b} | ${b} ${b} ${c} | ${c} ${c} ?`,a,s.filter(x=>x!==a).slice(0,3),"Das Endsymbol einer Gruppe startet die nächste Gruppe doppelt.");return makeTask(`v4-mat-hard-${a}${b}${c}${d4}`,"matrix","Welche Form schließt die Doppelrotation?",`${a} ${b} ${c} ${d4} | ${b} ${c} ${d4} ${a} | ${c} ${d4} ${a} ?`,b,s.filter(x=>x!==b).slice(0,3),"Vier Symbole rotieren zyklisch nach links.")}
function operator(seed:number,d:Difficulty){const x=randomInt(2,8),y=randomInt(2,7),v=seed%(d===3?7:d===2?6:3),fs=[{n:x+2*y,t:"a + 2b",e:"a + 2×b"},{n:x*y+y,t:"a×b + b",e:"a×b + b"},{n:2*x+y,t:"2a + b",e:"2×a + b"},{n:2*(x+y),t:"2(a+b)",e:"Summe verdoppeln"},{n:x*x-y,t:"a² − b",e:"a quadrieren, b abziehen"},{n:x*y+x-y,t:"ab + a − b",e:"Produkt + a − b"},{n:(x+y)*(x-y),t:"(a+b)(a−b)",e:"Summe mal Differenz"}],f=fs[v];return makeTask(`v4-op-${v}-${x}-${y}`,"operator","Berechne mit der neuen Operatorregel.",`Wenn a ★ b = ${f.t}, was ist ${x} ★ ${y}?`,String(f.n),[String(f.n+1),String(f.n-1),String(x*y)],`Regel: ${f.e}.`)}
const EX=[{v:["5","10","15","22","25"],c:"22",r:"Alle anderen sind durch 5 teilbar."},{v:["8","16","24","31","40"],c:"31",r:"Alle anderen sind durch 8 teilbar."},{v:["2","3","5","7","9","11"],c:"9",r:"Alle anderen sind Primzahlen."},{v:["12","18","24","30","35"],c:"35",r:"Alle anderen sind durch 6 teilbar."},{v:["9","16","25","36","45","49"],c:"45",r:"Alle anderen sind Quadratzahlen."},{v:["8","27","64","81","125"],c:"81",r:"Alle anderen sind Kubikzahlen."},{v:["21","28","35","42","50","56"],c:"50",r:"Alle anderen sind durch 7 teilbar."},{v:["16","25","36","49","63","64"],c:"63",r:"Alle anderen sind Quadratzahlen."},{v:["11","13","17","19","21","23"],c:"21",r:"Alle anderen sind Primzahlen."}];
function exclusion(seed:number,d:Difficulty){const start=d===1?0:d===2?2:5,span=d===1?3:d===2?4:4,e=EX[start+seed%span];return makeTask(`v4-exc-${e.v.join("-")}`,"exclusion","Welche Zahl passt nicht?",e.v.join(" · "),e.c,e.v.filter(x=>x!==e.c).slice(0,3),e.r)}
function spatial(seed:number,d:Difficulty){const dirs=["Norden","Osten","Süden","Westen"],start=seed%4,n=d===1?2:d===2?4:6;let p=start;const moves:string[]=[];for(let i=0;i<n;i++){const right=(seed+i*2)%5<3;p=(p+(right?1:3))%4;moves.push(right?"rechts":"links")}return makeTask(`v4-spa-${dirs[start]}-${moves.join("-")}`,"spatial","Wohin blickst du am Ende?",`Start: ${dirs[start]}. Drehungen: ${moves.join(" → ")}.`,dirs[p],dirs.filter(x=>x!==dirs[p]),`Führe alle ${n} Vierteldrehungen nacheinander aus.`)}
export function createLogicSession(bestScore:number):LogicSession{
 const difficulty=difficultyFromPercent((bestScore/LOGIC_SESSION_LENGTH)*100),seed=createSessionSeed();
 const candidates=Array.from({length:difficulty===3?5:4},(_,round)=>{const s=seed+round*97;return [sequence(s,difficulty),rule(s+11,difficulty),analogy(s+23,difficulty),deduction(s+37,difficulty),matrix(s+41,difficulty),operator(s+53,difficulty),exclusion(s+67,difficulty),spatial(s+79,difficulty)]}).flat();
 return {difficulty,tasks:finalizeBalancedSessionTasks("logic-v4",candidates,LOGIC_SESSION_LENGTH,144)};
}
