"use client";

import { useEffect, useState } from "react";
import { createLanguageSession, LANGUAGE_SESSION_LENGTH, LANGUAGE_STORAGE_KEY, type LanguageMode, type LanguageSession } from "@/lib/languageV2";
import { readRecentTaskIds, rememberTaskIds } from "@/lib/dynamicTraining";
import { applyAdaptiveDifficultyResult, createAdaptiveDifficultyState, difficultyLabel, type AdaptiveDifficultyState } from "@/lib/adaptiveDifficultyV5";
import { localizeTrainingText, localizedDifficultyLabel } from "@/lib/trainingLocale";
import { usePlatformLanguage } from "./PlatformLanguageProvider";
import styles from "./LanguageTraining.module.css";

type ModeStat={attempts:number;correct:number};
type Stats={sessions:number;bestScore:number;recentIds:string[];modeStats:Partial<Record<LanguageMode,ModeStat>>};
type Outcome={mode:LanguageMode;correct:boolean};
type Phase="intro"|"question"|"feedback"|"done";
const HISTORY_SCOPE="language-v4",HISTORY_LIMIT=144;
const initialStats:Stats={sessions:0,bestScore:0,recentIds:[],modeStats:{}};

export function LanguageTraining(){
  const {language,pick}=usePlatformLanguage(); const tr=(value:string|undefined)=>localizeTrainingText(value,language); const dl=(level:1|2|3)=>localizedDifficultyLabel(difficultyLabel(level),language);
  const labels:Record<LanguageMode,string>={synonym:pick("Synonyme","Synonyms"),antonym:pick("Antonyme","Antonyms"),analogy:pick("Analogien","Analogies"),category:pick("Kategorien","Categories"),wordfield:pick("Wortfelder","Semantic fields"),sentence:pick("Satzlogik","Sentence logic"),relation:pick("Beziehungen","Relations"),context:pick("Kontext","Context")};
  const [session,setSession]=useState<LanguageSession|null>(null),[index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[outcomes,setOutcomes]=useState<Outcome[]>([]),[phase,setPhase]=useState<Phase>("intro"),[stats,setStats]=useState<Stats>(initialStats),[adaptive,setAdaptive]=useState<AdaptiveDifficultyState>(createAdaptiveDifficultyState(1));
  useEffect(()=>{try{const raw=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(!raw)return;const saved=JSON.parse(raw) as Partial<Stats>;setStats({sessions:saved.sessions??0,bestScore:saved.bestScore??0,recentIds:saved.recentIds??[],modeStats:saved.modeStats??{}})}catch{setStats(initialStats)}},[]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(phase!=="question"||!session)return;const optionIndex=Number(event.key)-1;if(optionIndex>=0&&optionIndex<session.tasks[index].options.length)answer(optionIndex)};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)});

  function currentHistory(){return [...new Set([...stats.recentIds,...readRecentTaskIds(HISTORY_SCOPE,HISTORY_LIMIT),...(session?.tasks.map(item=>item.id)??[])])].slice(-HISTORY_LIMIT)}
  function start(){const merged=currentHistory();const next=createLanguageSession(stats.bestScore,merged,stats.sessions,undefined,language);setSession(next);setAdaptive(createAdaptiveDifficultyState(next.difficulty));setIndex(0);setSelected(null);setOutcomes([]);setPhase("question")}
  function answer(optionIndex:number){if(!session||phase!=="question")return;const current=session.tasks[index],correct=optionIndex===current.answer,nextAdaptive=applyAdaptiveDifficultyResult(adaptive,correct);setSelected(optionIndex);setOutcomes(values=>[...values,{mode:current.mode,correct}]);setAdaptive(nextAdaptive);if(nextAdaptive.transition!=="hold"&&nextAdaptive.level!==session.difficulty){const replacement=createLanguageSession(stats.bestScore,currentHistory(),stats.sessions,nextAdaptive.level,language);setSession({...replacement,difficulty:nextAdaptive.level,tasks:[...session.tasks.slice(0,index+1),...replacement.tasks.slice(index+1)]})}setPhase("feedback")}
  function next(){if(!session)return;if(index<session.tasks.length-1){setIndex(value=>value+1);setSelected(null);setPhase("question");return}const score=outcomes.filter(item=>item.correct).length,modeStats={...stats.modeStats};outcomes.forEach(item=>{const current=modeStats[item.mode]??{attempts:0,correct:0};modeStats[item.mode]={attempts:current.attempts+1,correct:current.correct+(item.correct?1:0)}});const sessionIds=session.tasks.map(item=>item.id);rememberTaskIds(HISTORY_SCOPE,sessionIds,HISTORY_LIMIT);const nextStats={sessions:stats.sessions+1,bestScore:Math.max(stats.bestScore,score),recentIds:[...new Set([...stats.recentIds,...sessionIds])].slice(-HISTORY_LIMIT),modeStats};setStats(nextStats);try{localStorage.setItem(LANGUAGE_STORAGE_KEY,JSON.stringify(nextStats))}catch{}setPhase("done")}

  const current=session?.tasks[index],score=outcomes.filter(item=>item.correct).length,percent=session?Math.round(score/session.tasks.length*100):0;
  return <section className={styles.trainer} aria-live="polite" data-adaptive-level={adaptive.level}>
    <div className={styles.stats}><span>Sessions <strong>{stats.sessions}</strong></span><span>{pick("Bestwert","Best score")} <strong>{stats.bestScore}/{LANGUAGE_SESSION_LENGTH}</strong></span><span>{session?`${pick("Dynamik","Dynamic")} ${adaptive.level} · ${dl(adaptive.level)}`:"Language Lab · Adaptive Difficulty V5"}</span></div>
    {phase==="intro"&&<div className={styles.stage}><p className="eyebrow">8 {pick("Sprachmodi","language modes")} · Adaptive Difficulty V5</p><h2>{pick("Wörter verstehen. Beziehungen erkennen. Kontext präzise deuten.","Understand words. Identify relations. Interpret context precisely.")}</h2><p>{pick("Language V5 passt die sprachliche Tiefe jetzt auch während der laufenden Session an. Drei sichere Treffer können die folgenden Aufgaben um eine Stufe anheben; zwei Fehler in Folge stabilisieren um genau eine Stufe. Einzelne Antworten lösen keinen abrupten Sprung aus.","Language V5 now adapts linguistic depth during the active session. Three reliable correct answers can raise following tasks by one level; two consecutive errors reduce it by exactly one level. Single answers never trigger an abrupt jump.")}</p><div className={styles.modeGrid}>{Object.values(labels).map(label=><span key={label}>{label}</span>)}</div><button className="primary trainingButton" type="button" onClick={start}>{pick("Language Session starten","Start Language session")}</button></div>}
    {phase==="question"&&current&&session&&<div className={styles.stage}><p className="eyebrow">{labels[current.mode]} · {pick("Aufgabe","Task")} {index+1}/{session.tasks.length} · {pick("Dynamik","Dynamic")} {adaptive.level} {dl(adaptive.level)}</p><h2>{tr(current.prompt)}</h2><div className={styles.prompt}>{tr(current.detail)}</div><div className={styles.options}>{current.options.map((option,optionIndex)=><button className={styles.option} key={`${current.id}-${optionIndex}`} type="button" onClick={()=>answer(optionIndex)}><kbd>{optionIndex+1}</kbd><span>{tr(option)}</span></button>)}</div></div>}
    {phase==="feedback"&&current&&selected!==null&&<div className={`${styles.stage} ${styles.feedback}`}><p className={`${styles.feedbackBadge} ${selected===current.answer?styles.correct:styles.incorrect}`}>{selected===current.answer?pick("Richtig","Correct"):pick("Noch nicht","Not quite")}</p><h2>{selected===current.answer?pick("Sprachliche Beziehung erkannt.","Language relation identified."):`${pick("Richtig wäre","Correct answer")}: ${tr(current.options[current.answer])}`}</h2><p>{tr(current.explanation)}</p><p><strong>Adaptive Difficulty V5:</strong> {tr(adaptive.reason)}</p><button className="primary trainingButton" type="button" onClick={next}>{session&&index===session.tasks.length-1?pick("Auswertung","Results"):pick("Nächste Aufgabe","Next task")}</button></div>}
    {phase==="done"&&session&&<div className={styles.stage}><p className="eyebrow">{pick("Session abgeschlossen","Session complete")} · {pick("Endniveau","Final level")} {adaptive.level} {dl(adaptive.level)}</p><h2>{percent}% {pick("richtig","correct")}</h2><div className={styles.score}><strong>{score}</strong><span>/ {session.tasks.length}</span></div><div className={styles.modeStats}>{(Object.entries(stats.modeStats) as [LanguageMode,ModeStat][]).map(([mode,value])=><div key={mode}><span>{labels[mode]}</span><strong>{value.attempts?Math.round(value.correct/value.attempts*100):0}%</strong></div>)}</div><p>{pick("Die nächste Session startet wieder evidenzbasiert und passt sich anschließend schrittweise innerhalb der Einheit an.","The next session starts from evidence-based difficulty and then adapts gradually within the session.")}</p><button className="primary trainingButton" type="button" onClick={start}>{pick("Neue Language Session","New Language session")}</button></div>}
  </section>;
}
