"use client";

import { useEffect, useState } from "react";
import { createVisualSession, VISUAL_SESSION_LENGTH, VISUAL_STORAGE_KEY, type VisualMode, type VisualSession } from "@/lib/visualV2";
import { applyAdaptiveDifficultyResult, createAdaptiveDifficultyState, difficultyLabel, type AdaptiveDifficultyState } from "@/lib/adaptiveDifficultyV5";
import { localizedDifficultyLabel } from "@/lib/trainingLocale";
import { localizeSessionText } from "@/lib/sessionLocale";
import { usePlatformLanguage } from "./PlatformLanguageProvider";
import styles from "./VisualTraining.module.css";

type ModeStat = { attempts: number; correct: number };
type VisualStats = { sessions: number; bestScore: number; modeStats: Partial<Record<VisualMode, ModeStat>> };
type Outcome = { mode: VisualMode; correct: boolean };
type Phase = "intro" | "preview" | "question" | "feedback" | "done";
const initialStats: VisualStats = { sessions: 0, bestScore: 0, modeStats: {} };

export function VisualTraining() {
  const {language,pick}=usePlatformLanguage(); const tr=(value:string|undefined)=>localizeSessionText(value,language); const dl=(level:1|2|3)=>localizedDifficultyLabel(difficultyLabel(level),language);
  const labels: Record<VisualMode, string> = { rotation:"Rotation",mirror:pick("Spiegelung","Reflection"),pattern:pick("Musterreihe","Pattern sequence"),matrix:"Matrix",position:pick("Positionswechsel","Position shift"),search:pick("Visuelle Suche","Visual search"),compare:pick("Formvergleich","Shape comparison"),memory:pick("Kurzzeitgedächtnis","Short-term memory") };
  const positionLabels=language==="en"?["top left","top center","top right","middle left","center","middle right","bottom left","bottom center","bottom right"]:["oben links","oben Mitte","oben rechts","Mitte links","Mitte","Mitte rechts","unten links","unten Mitte","unten rechts"];
  const [session,setSession]=useState<VisualSession|null>(null); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [outcomes,setOutcomes]=useState<Outcome[]>([]); const [phase,setPhase]=useState<Phase>("intro"); const [stats,setStats]=useState<VisualStats>(initialStats); const [adaptive,setAdaptive]=useState<AdaptiveDifficultyState>(createAdaptiveDifficultyState(1)); const current=session?.tasks[index];
  useEffect(()=>{try{const raw=localStorage.getItem(VISUAL_STORAGE_KEY);if(!raw)return;const parsed=JSON.parse(raw) as Partial<VisualStats>;setStats({sessions:parsed.sessions??0,bestScore:parsed.bestScore??0,modeStats:parsed.modeStats??{}})}catch{setStats(initialStats)}},[]);
  useEffect(()=>{if(phase!=="preview"||!current?.previewMs)return;const timer=window.setTimeout(()=>setPhase("question"),current.previewMs);return()=>window.clearTimeout(timer)},[phase,current]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(phase!=="question"||!current)return;const optionIndex=Number(event.key)-1;if(optionIndex>=0&&optionIndex<current.options.length)answer(optionIndex)};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)});
  function enterTask(active:VisualSession,taskIndex:number){setIndex(taskIndex);setSelected(null);setPhase(active.tasks[taskIndex].mode==="memory"?"preview":"question")}
  function start(){const nextSession=createVisualSession(stats.bestScore,stats.sessions);setSession(nextSession);setAdaptive(createAdaptiveDifficultyState(nextSession.difficulty));setOutcomes([]);enterTask(nextSession,0)}
  function answer(optionIndex:number){if(!current||!session||phase!=="question")return;const correct=optionIndex===current.answer;const nextAdaptive=applyAdaptiveDifficultyResult(adaptive,correct);setSelected(optionIndex);setOutcomes(v=>[...v,{mode:current.mode,correct}]);setAdaptive(nextAdaptive);if(nextAdaptive.transition!=="hold"&&nextAdaptive.level!==session.difficulty){const replacement=createVisualSession(stats.bestScore,stats.sessions,nextAdaptive.level);setSession({...replacement,difficulty:nextAdaptive.level,tasks:[...session.tasks.slice(0,index+1),...replacement.tasks.slice(index+1)]})}setPhase("feedback")}
  function next(){if(!session)return;if(index<session.tasks.length-1){enterTask(session,index+1);return}const score=outcomes.filter(i=>i.correct).length;const modeStats={...stats.modeStats};outcomes.forEach(item=>{const previous=modeStats[item.mode]??{attempts:0,correct:0};modeStats[item.mode]={attempts:previous.attempts+1,correct:previous.correct+(item.correct?1:0)}});const nextStats={sessions:stats.sessions+1,bestScore:Math.max(stats.bestScore,score),modeStats};setStats(nextStats);try{localStorage.setItem(VISUAL_STORAGE_KEY,JSON.stringify(nextStats))}catch{}setPhase("done")}
  const score=outcomes.filter(i=>i.correct).length; const percent=session?Math.round((score/session.tasks.length)*100):0;

  function questionVisual(){if(!current)return null;if(current.mode==="compare"){const separator=current.visual.indexOf("|");const left=separator>=0?current.visual.slice(0,separator):current.visual;const right=separator>=0?current.visual.slice(separator+1):[];return <div className={styles.compareBoard} aria-label={`${pick("Reihe A","Row A")}: ${left.join(" ")}. ${pick("Reihe B","Row B")}: ${right.join(" ")}`}><div className={styles.compareRow}><strong>{pick("Reihe A","Row A")}</strong><div>{left.map((item,itemIndex)=><span key={`a-${item}-${itemIndex}`}>{item}</span>)}</div></div><div className={styles.compareDivider} aria-hidden="true"><span>{pick("vergleichen","compare")}</span></div><div className={styles.compareRow}><strong>{pick("Reihe B","Row B")}</strong><div>{right.map((item,itemIndex)=><span key={`b-${item}-${itemIndex}`}>{item}</span>)}</div></div></div>;}if(current.mode==="position"){const startIndex=current.visual.findIndex(item=>item==="●");const moves=current.id.split("-").slice(2).join("").split("").filter(item=>["↑","→","↓","←"].includes(item));return <div className={styles.positionExercise}><div className={styles.movementStrip} aria-label={`${pick("Bewegungsfolge","Movement sequence")}: ${moves.join(" ")}`}><strong>{pick("Bewegungsfolge","Movement sequence")}</strong><div>{moves.map((move,moveIndex)=><span key={`${move}-${moveIndex}`}>{move}</span>)}</div></div><div className={`${styles.visualBoard} ${styles.gridBoard} ${styles.positionBoard}`} aria-label={`${pick("Startposition","Start position")}: ${positionLabels[startIndex]??pick("unbekannt","unknown")}`}>{current.visual.map((item,itemIndex)=><span key={`${item}-${itemIndex}`} className={styles.positionCell} data-start={itemIndex===startIndex} aria-label={itemIndex===startIndex?`${pick("Start","Start")}: ${positionLabels[itemIndex]}`:positionLabels[itemIndex]}>{itemIndex===startIndex?<><b>START</b><i aria-hidden="true">●</i></>:<i aria-hidden="true">·</i>}</span>)}</div></div>;}return <div className={`${styles.visualBoard} ${current.visual.length===9?styles.gridBoard:""}`} aria-label={current.visual.join(" ")}>{current.visual.map((item,itemIndex)=><span key={`${item}-${itemIndex}`}>{item}</span>)}</div>;}

  return <section className={styles.trainer} aria-live="polite" data-adaptive-level={adaptive.level}>
    <div className={styles.stats}><span>Sessions <strong>{stats.sessions}</strong></span><span>{pick("Bestwert","Best score")} <strong>{stats.bestScore}/{VISUAL_SESSION_LENGTH}</strong></span><span>{session?`${pick("Dynamik","Dynamic")} ${adaptive.level} · ${dl(adaptive.level)}`:"Visual Lab · Adaptive Difficulty V5"}</span></div>
    {phase==="intro"&&<div className={styles.stage}><p className="eyebrow">8 {pick("visuelle Trainingsmodi","visual training modes")} · Adaptive Difficulty V5</p><h2>{pick("Sehen. Vergleichen. Erinnern. Räumlich denken.","See. Compare. Remember. Think spatially.")}</h2><p>{pick("Visual V5 passt die visuelle Schwierigkeit jetzt auch während der laufenden Session an. Drei sichere Treffer können die folgenden Aufgaben um genau eine Stufe anheben; zwei Fehler in Folge stabilisieren um genau eine Stufe. Einzelne Antworten lösen keinen abrupten Sprung aus.","Visual V5 now adapts visual difficulty during the active session. Three reliable correct answers can raise following tasks by exactly one level; two consecutive errors reduce it by exactly one level. Single answers never trigger an abrupt jump.")}</p><div className={styles.modeGrid}>{Object.values(labels).map(label=><span key={label}>{label}</span>)}</div><button className="primary trainingButton" type="button" onClick={start}>{pick("Visual Session starten","Start Visual session")}</button></div>}
    {phase==="preview"&&current?.preview&&<div className={styles.stage} data-visual-mode={current.mode}><p className="eyebrow">{labels[current.mode]} · {pick("Aufgabe","Task")} {index+1}/{VISUAL_SESSION_LENGTH} · {pick("Dynamik","Dynamic")} {adaptive.level} {dl(adaptive.level)}</p><h2>{pick("Präge dir die Reihenfolge ein.","Memorize the sequence.")}</h2><div className={styles.previewBadge}>{pick("Nur kurz sichtbar","Visible briefly")}</div><div className={styles.visualBoard} aria-label={`${pick("Zu merkende Folge","Sequence to remember")}: ${current.preview.join(" ")}`}>{current.preview.map((item,itemIndex)=><span key={`${item}-${itemIndex}`}>{item}</span>)}</div><p>{pick("Danach wird nach einer Position in dieser Folge gefragt.","You will then be asked about one position in this sequence.")}</p></div>}
    {phase==="question"&&current&&session&&<div className={styles.stage} data-visual-mode={current.mode}><p className="eyebrow">{labels[current.mode]} · {pick("Aufgabe","Task")} {index+1}/{session.tasks.length} · {pick("Dynamik","Dynamic")} {adaptive.level} {dl(adaptive.level)}</p><h2>{tr(current.prompt)}</h2>{questionVisual()}<div className={styles.options}>{current.options.map((option,optionIndex)=><button key={`${current.id}-${optionIndex}`} type="button" onClick={()=>answer(optionIndex)}><kbd>{optionIndex+1}</kbd>{tr(option)}</button>)}</div></div>}
    {phase==="feedback"&&current&&selected!==null&&<div className={styles.stage}><p className={`${styles.feedbackBadge} ${selected===current.answer?styles.correct:styles.incorrect}`}>{selected===current.answer?pick("Richtig","Correct"):pick("Noch nicht","Not quite")}</p><h2>{selected===current.answer?pick("Visuell korrekt erkannt.","Visual pattern identified correctly."):`${pick("Richtig wäre","Correct answer")}: ${tr(current.options[current.answer])}`}</h2><p>{tr(current.explanation)}</p><p><strong>Adaptive Difficulty V5:</strong> {tr(adaptive.reason)}</p><button className="primary trainingButton" type="button" onClick={next}>{session&&index===session.tasks.length-1?pick("Auswertung","Results"):pick("Nächste Aufgabe","Next task")}</button></div>}
    {phase==="done"&&session&&<div className={styles.stage}><p className="eyebrow">{pick("Session abgeschlossen","Session complete")} · {pick("Endniveau","Final level")} {adaptive.level} {dl(adaptive.level)}</p><h2>{percent}% {pick("richtig","correct")}</h2><div className={styles.score}><strong>{score}</strong><span>/ {session.tasks.length}</span></div><div className={styles.modeStats}>{(Object.entries(stats.modeStats) as [VisualMode,ModeStat][]).map(([mode,value])=><div key={mode}><span>{labels[mode]}</span><strong>{value.attempts?Math.round((value.correct/value.attempts)*100):0}%</strong></div>)}</div><p>{pick("Die nächste Session startet wieder evidenzbasiert und passt sich anschließend schrittweise innerhalb der Einheit an.","The next session starts from evidence-based difficulty and then adapts gradually within the session.")}</p><button className="primary trainingButton" type="button" onClick={start}>{pick("Neue Visual Session","New Visual session")}</button></div>}
  </section>;
}
